"""initial schema with unique platform per aid

Revision ID: 90b3e1f31f51
Revises:
Create Date: 2026-09-29 11:38:19.754056

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "90b3e1f31f51"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "locales_user_account",
        sa.Column(
            "aid",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Global account id",
        ),
        sa.Column(
            "language_code",
            sa.String(length=32),
            nullable=False,
            comment="Preferred locale code",
        ),
        sa.Column(
            "primary_platform",
            sa.String(length=64),
            nullable=False,
            comment="Platform that created this account",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("aid", name=op.f("pk_locales_user_account")),
    )
    op.create_table(
        "locales_account_audit_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("operation", sa.String(length=32), nullable=False),
        sa.Column("platform", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=191), nullable=False),
        sa.Column("old_aid", sa.Integer(), nullable=False),
        sa.Column("new_aid", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["new_aid"],
            ["locales_user_account.aid"],
            name=op.f("fk_locales_account_audit_log_new_aid_locales_user_account"),
        ),
        sa.ForeignKeyConstraint(
            ["old_aid"],
            ["locales_user_account.aid"],
            name=op.f("fk_locales_account_audit_log_old_aid_locales_user_account"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_locales_account_audit_log")),
    )
    with op.batch_alter_table("locales_account_audit_log", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_locales_account_audit_log_platform"),
            ["platform"],
            unique=False,
        )

    op.create_table(
        "locales_binding_token",
        sa.Column("aid", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("language_code", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["aid"],
            ["locales_user_account.aid"],
            name=op.f("fk_locales_binding_token_aid_locales_user_account"),
        ),
        sa.PrimaryKeyConstraint("aid", name=op.f("pk_locales_binding_token")),
    )
    with op.batch_alter_table("locales_binding_token", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_locales_binding_token_expires_at"),
            ["expires_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_locales_binding_token_token_hash"),
            ["token_hash"],
            unique=True,
        )

    op.create_table(
        "locales_platform_binding",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("platform", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=191), nullable=False),
        sa.Column("aid", sa.Integer(), nullable=False),
        sa.Column("created_aid", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["aid"],
            ["locales_user_account.aid"],
            name=op.f("fk_locales_platform_binding_aid_locales_user_account"),
        ),
        sa.ForeignKeyConstraint(
            ["created_aid"],
            ["locales_user_account.aid"],
            name=op.f("fk_locales_platform_binding_created_aid_locales_user_account"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_locales_platform_binding")),
        sa.UniqueConstraint("aid", "platform", name="uq_locales_aid_platform"),
        sa.UniqueConstraint("platform", "user_id", name="uq_locales_platform_user"),
    )
    with op.batch_alter_table("locales_platform_binding", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_locales_platform_binding_aid"), ["aid"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_locales_platform_binding_created_aid"),
            ["created_aid"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_locales_platform_binding_platform"),
            ["platform"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("locales_platform_binding", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_locales_platform_binding_platform"))
        batch_op.drop_index(batch_op.f("ix_locales_platform_binding_created_aid"))
        batch_op.drop_index(batch_op.f("ix_locales_platform_binding_aid"))

    op.drop_table("locales_platform_binding")
    with op.batch_alter_table("locales_binding_token", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_locales_binding_token_token_hash"))
        batch_op.drop_index(batch_op.f("ix_locales_binding_token_expires_at"))

    op.drop_table("locales_binding_token")
    with op.batch_alter_table("locales_account_audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_locales_account_audit_log_platform"))

    op.drop_table("locales_account_audit_log")
    op.drop_table("locales_user_account")
    # ### end Alembic commands ###
